#!/usr/bin/env python3
"""
GameplayTag INI -> TypeScript mapping generator.

Usage:
    python3 gameplay_tag_ini_to_ts.py --input DefaultGameplayTags.ini --output GameplayTags.generated.ts

Supported input patterns:
    +GameplayTags=(Tag="Action.Cancel.Jump")
    GameplayTags=(Tag="Action.Cancel.Jump")
    Tag="Action.Cancel.Jump"

It generates a TS file with:
    export const GameplayTagNames = { ... } as const;
    export type GameplayTagName = typeof GameplayTagNames[keyof typeof GameplayTagNames];
    export const GameplayTags = { ... } as const;
"""

import argparse
import re
import sys
from collections import OrderedDict
from pathlib import Path
from typing import Dict, List, Optional, Sequence

TAG_ENTRY_RE = re.compile(r"\bTag\s*=\s*(?:\"(?P<quoted>[^\"]+)\"|(?P<plain>[^,\)\s]+))")
LINE_TAG_RE = re.compile(r"\bGameplayTag(?:s|List)\s*=\s*\((?P<content>.*)\)")
SIMPLE_TAG_RE = re.compile(r"^\s*Tag\s*=\s*(?:\"(?P<quoted>[^\"]+)\"|(?P<plain>[^\s]+))")


def normalize_identifier(name: str) -> str:
    if not name:
        return "Tag"
    # Generate safe TS identifier
    token = re.sub(r"[^0-9A-Za-z]+", "_", name)
    token = re.sub(r"_+", "_", token)
    token = token.strip("_")
    if not token:
        token = "Tag"
    if token[0].isdigit():
        token = f"_{token}"
    return token


def segment_to_key(segment: str) -> str:
    return normalize_identifier(segment)


def flatten_path_to_constant(tag: str) -> str:
    segments = [segment_to_key(part) for part in tag.split(".") if part]
    if not segments:
        return "Tag"
    return "".join([seg[0].upper() + seg[1:] if seg else "" for seg in segments])


def parse_tag_line(line: str) -> Optional[str]:
    m = TAG_ENTRY_RE.search(line)
    if m:
        return m.group("quoted") or m.group("plain")
    return None


def read_tags_from_file(path: Path) -> List[str]:
    tags: List[str] = []
    with path.open("r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith(";") or line.startswith("#"):
                continue
            parsed = parse_tag_line(line)
            if parsed:
                tags.append(parsed)
    return tags


def build_nested_object(tag_names: Sequence[str]) -> Dict[str, object]:
    nested: Dict[str, object] = {}
    for tag in tag_names:
        path = [segment_to_key(part) for part in tag.split(".") if part]
        if not path:
            continue
        current = nested
        for idx, segment in enumerate(path):
            if idx == len(path) - 1:
                current.setdefault(segment, tag)
            else:
                current = current.setdefault(segment, {})  # type: ignore
    return nested


def render_ts_object(obj: object, indent: int = 0) -> str:
    pad = " " * indent
    if isinstance(obj, dict):
        lines = ["{" ]
        for i, (key, value) in enumerate(obj.items()):
            lines.append(f"{pad}    {key}: {render_ts_object(value, indent + 4)}{',' if i < len(obj) - 1 else ''}")
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    if isinstance(obj, str):
        return f'"{obj}"'
    raise TypeError(f"Unsupported object type: {type(obj)}")


def generate_ts(tag_names: Sequence[str], header_comment: str, const_name: str = "GameplayTagNames", nested_name: str = "GameplayTags") -> str:
    unique_tags = []
    seen = set()
    for t in tag_names:
        if t not in seen:
            seen.add(t)
            unique_tags.append(t)

    entries = []
    for tag in unique_tags:
        key = flatten_path_to_constant(tag)
        if key in [existing[0] for existing in entries]:
            suffix = 2
            alt = f"{key}{suffix}"
            while alt in [existing[0] for existing in entries]:
                suffix += 1
                alt = f"{key}{suffix}"
            key = alt
        entries.append((key, tag))

    lines = ["/**", f" * {header_comment}", " * Generated by gameplay_tag_ini_to_ts.py", " */", "", f"export const {const_name} = {{"]
    for key, tag in entries:
        lines.append(f"    {key}: \"{tag}\",")
    lines.append(f"}} as const;\n")
    lines.append(f"export type {const_name}Value = typeof {const_name}[keyof typeof {const_name}];\n")

    nested = build_nested_object(unique_tags)
    lines.append(f"export const {nested_name} = {render_ts_object(nested)} as const;\n")

    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a TS GameplayTag mapping from a UE ini file.")
    parser.add_argument("--input", "-i", required=True, help="Source ini/ini-like file path")
    parser.add_argument("--output", "-o", default="GameplayTags.generated.ts", help="Target TS file path")
    parser.add_argument("--header", default="Gameplay tag mapping generated from ini.", help="Header comment text")
    parser.add_argument("--const-name", default="GameplayTagNames", help="Name of the flat tag constant")
    parser.add_argument("--nested-name", default="GameplayTags", help="Name of the nested tag object")
    parser.add_argument("--dry-run", action="store_true", help="Print generated content instead of writing file")
    args = parser.parse_args(argv)

    path = Path(args.input)
    if not path.exists():
        print(f"Error: input file not found: {path}", file=sys.stderr)
        return 1

    tags = read_tags_from_file(path)
    if not tags:
        print(f"Warning: no GameplayTags found in {path}", file=sys.stderr)

    generated = generate_ts(tags, args.header, args.const_name, args.nested_name)
    if args.dry_run:
        print(generated)
        return 0

    out_path = Path(args.output)
    out_path.write_text(generated, encoding="utf-8")
    print(f"Wrote {out_path} ({len(tags)} tags)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
