/**
 * Gameplay tag mapping generated from ini.
 * Generated by gameplay_tag_ini_to_ts.py
 */

export const GameplayTagNames = {
    ActionCancelDash: "Action.Cancel.Dash",
    ActionCancelJump: "Action.Cancel.Jump",
    ActionCombatAttacking: "Action.Combat.Attacking",
} as const;

export type GameplayTagNamesValue = typeof GameplayTagNames[keyof typeof GameplayTagNames];

export const GameplayTags = {
    Action: {
        Cancel: {
            Dash: "Action.Cancel.Dash",
            Jump: "Action.Cancel.Jump"
        },
        Combat: {
            Attacking: "Action.Combat.Attacking"
        }
    }
} as const;
